# Generated by Django 6.0.3 on 2026-03-18 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productivity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "done",
                    models.TextField(
                        blank=True, default="", help_text="Что сделано сегодня"
                    ),
                ),
                (
                    "planned",
                    models.TextField(
                        blank=True, default="", help_text="Планы на завтра"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Свободные заметки"
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("great", "Отлично"),
                            ("good", "Хорошо"),
                            ("okay", "Нормально"),
                            ("bad", "Плохо"),
                            ("terrible", "Ужасно"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "energy_level",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Уровень энергии 0-5"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "daily log",
                "verbose_name_plural": "daily logs",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
