# Generated by Django 6.0.3 on 2026-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productivity", "0002_dailylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="target_days",
            field=models.PositiveIntegerField(
                default=30, help_text="Цель: сколько дней длится привычка"
            ),
        ),
    ]
