# Generated by Django 6.0.3 on 2026-03-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_format",
            field=models.CharField(default="DD.MM.YYYY", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="number_format",
            field=models.CharField(default="1 000,00", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="week_start",
            field=models.CharField(default="mon", max_length=3),
        ),
    ]
