# Generated by Django 6.0.3 on 2026-03-26 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('module_title', models.CharField(blank=True, default='', max_length=255)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_messages', to='learning.learninggoal')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_messages', to='learning.learningtask')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['goal', 'created_at'], name='learning_tu_goal_id_ed5569_idx')],
            },
        ),
    ]
