# Generated by Django 6.0.3 on 2026-03-26 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(db_index=True, max_length=50)),
                ('channel', models.CharField(default='web', max_length=20)),
                ('prompt_version', models.CharField(default='v1', max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cached_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Call Log',
                'verbose_name_plural': 'AI Call Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['method', 'created_at'], name='ai_core_aic_method_79edcf_idx'), models.Index(fields=['user', 'created_at'], name='ai_core_aic_user_id_1de7ad_idx')],
            },
        ),
    ]
